import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://cdms-staging.ripplr.in/login');
  await page.getByRole('textbox', { name: 'User ID User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID User ID' }).fill('admin@ripplr.in');
  await page.getByRole('textbox', { name: 'Password Password' }).click();
  await page.getByRole('textbox', { name: 'Password Password' }).fill('M@ver!ck');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('menuitem', { name: 'Dashboard' }).getByRole('link').click();
  await page.getByText('Sales Order').click();
  await page.getByRole('link', { name: 'Order Management' }).click();
  await page.locator('div').filter({ hasText: /^Returns$/ }).nth(2).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByText('Delivery Allocation').click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByText('Return To FC', { exact: true }).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByText('Goods Received Note').click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByText('Onboarding').nth(1).click();
  await page.getByText('Company').click();
  await page.getByRole('link', { name: 'On Boarding' }).click();
  await page.locator('div').filter({ hasText: /^Client$/ }).nth(2).click();
  await page.getByText('>On Boarding>Clientadmin').click();
  await page.getByText('>On Boarding>Client').click();
  await page.locator('div').filter({ hasText: /^Brand$/ }).nth(2).click();
  await page.getByRole('link', { name: 'On Boarding' }).click();
  await page.locator('div').filter({ hasText: /^FC$/ }).nth(2).click();
  await page.getByRole('link', { name: 'On Boarding' }).click();
  await page.getByText('Store').nth(2).click();
  await page.getByRole('link', { name: 'On Boarding' }).click();
  await page.locator('div').filter({ hasText: /^Store Category$/ }).nth(2).click();
  await page.getByRole('link', { name: 'On Boarding' }).click();
  await page.getByText('User').nth(1).click();
  await page.getByRole('link', { name: 'On Boarding' }).click();
  await page.getByText('Masters').nth(1).click();
  await page.getByRole('link', { name: 'On Boarding' }).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByText('Adapter Uploads').nth(1).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.locator('div').filter({ hasText: /^Downloads$/ }).nth(1).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByText('WMS Logs').nth(1).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByText('Cheque bounce', { exact: true }).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByText('Retailer Ledger').click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.locator('div').filter({ hasText: /^Collection Automation$/ }).nth(1).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.locator('div:nth-child(13) > .sc-eYPhOV > .sc-evZas > svg').click();
  await page.getByText('Order Management').click();
  await page.getByRole('link', { name: 'Sales Order' }).click();
  await page.getByRole('button', { name: 'Mark ECO Bills' }).click();
  await page.goto('https://cdms-staging.ripplr.in/order-management/sales-order?query=&offset=0&limit=10&currentPage=1');
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByText('Order Management').click();
  await page.getByRole('link', { name: 'Sales Order' }).click();
  await page.getByRole('button', { name: 'Mark Pay On Delivery' }).click();
  await page.getByRole('link', { name: 'Sales Order' }).nth(1).click();
  await page.getByRole('button', { name: 'Blocked Order' }).click();
  await page.getByRole('link', { name: 'Sales Order' }).nth(1).click();
  await page.getByRole('row', { name: '19/07/2025 Test Fc (TF: CSKAA' }).getByRole('img').nth(1).click();
  await page.getByRole('tab', { name: 'Delivery Details' }).click();
  await page.getByRole('tab', { name: 'Proof of Delivery' }).click();
  await page.getByRole('tab', { name: 'Order Journey' }).click();
  await page.getByRole('tab', { name: 'Collection History' }).click();
  await page.locator('div').filter({ hasText: /^Sales Return$/ }).first().click();
  await page.getByRole('menuitem', { name: 'Sales Order' }).getByRole('link').click();
  await page.getByRole('link', { name: 'Returns', exact: true }).click();
  await page.getByRole('button', { name: 'Add Sales return' }).click();
  await page.getByRole('menuitem', { name: 'Returns', exact: true }).getByRole('link').click();
  await page.locator('td:nth-child(12)').first().click();
  await page.getByRole('menuitem', { name: 'Returns', exact: true }).getByRole('link').click();
  await page.locator('label').filter({ hasText: 'To Date' }).locator('div').nth(1).click();
  await page.locator('label').filter({ hasText: 'To Date' }).locator('div').nth(1).click();
  await page.getByRole('row', { name: 'SI27RTEX4 HUL TLBL YI26TYEGG2' }).getByRole('link').click();
  await page.getByRole('link', { name: 'Brand Sales Return', exact: true }).click();
  await page.getByText('Logistics Management').click();
  await page.getByRole('link', { name: 'Delivery Allocation' }).click();
  await page.getByRole('button', { name: 'Create Delivery Allocation' }).click();
  await page.getByRole('link', { name: 'Delivery Allocation' }).nth(1).click();
  await page.getByRole('row', { name: 'TN09TN9090 19/07/2025, 02:18' }).getByRole('link').click();
  await page.getByRole('link', { name: 'Delivery Allocation' }).nth(1).click();
  await page.getByRole('link', { name: 'Return To Fc' }).click();
  await page.getByRole('row', { name: '19/07/2025 TN09TN9090 Veera 9898989800 Delivery 9898989816 Complete 19/07/2025, 02:24 PM Generate PDF', exact: true }).getByRole('link').click();
  await page.getByRole('link', { name: 'Return To FC', exact: true }).click();
  await page.getByText('Warehouse Management').click();
  await page.getByRole('link', { name: 'WMS Logs' }).click();
  await page.getByRole('link', { name: 'PO Logs' }).click();
  await page.getByRole('menuitem', { name: 'ASN' }).locator('div').click();
  await page.getByRole('link', { name: 'GRN' }).click();
  await page.getByText('Onboarding').click();
  await page.getByRole('link', { name: 'Company' }).click();
  await page.getByRole('button', { name: 'Add Company' }).click();
  await page.getByRole('link', { name: 'Client' }).click();
  await page.getByRole('button', { name: 'Add Client' }).click();
  await page.getByRole('link', { name: 'Brand' }).click();
  await page.getByRole('button', { name: 'Add Brand' }).click();
  await page.getByRole('link', { name: 'FC' }).click();
  await page.getByRole('tooltip', { name: 'Click to cancel sorting' }).click();
  await page.getByRole('button', { name: 'Add FC' }).click();
  await page.getByRole('link', { name: 'Store', exact: true }).click();
  await page.getByRole('button', { name: 'Add Store' }).click();
  await page.getByRole('link', { name: 'Store Category' }).click();
  await page.getByRole('button', { name: 'Add Store Category' }).click();
  await page.getByRole('link', { name: 'User' }).click();
  await page.getByRole('button', { name: 'Add User' }).click();
  await page.getByRole('link', { name: 'Salesman' }).click();
  await page.getByRole('button', { name: 'Add Salesman' }).click();
  await page.getByText('Masters').click();
  await page.getByRole('link', { name: 'Bank' }).click();
  await page.getByRole('button', { name: 'Add Bank' }).click();
  await page.getByRole('link', { name: 'Pincode' }).click();
  await page.getByRole('link', { name: 'Pack Master' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByText('Onboarding').click();
  await page.getByText('Finance Management').click();
  await page.getByRole('link', { name: 'Retailer Ledger' }).click();
  await page.getByRole('link', { name: 'FinOps' }).click();
  await page.getByText('Cheque Bounce', { exact: true }).click();
  await page.getByRole('link', { name: 'Cheque Bounce List' }).click();
  await page.getByRole('button', { name: 'Add Cheque Bounce' }).click();
  await page.getByRole('button', { name: 'Add Cheque Bounce' }).click();
  await page.getByRole('button', { name: 'Add Cheque Bounce' }).click();
  await page.getByRole('button', { name: 'Add Cheque Bounce' }).click();
  await page.getByRole('button', { name: 'Upload' }).click();
  await page.getByLabel('Upload Csv').locator('label span').nth(1).click();
  await page.getByTitle('Sales Order').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'Downloads' }).click();
  await page.getByRole('button', { name: 'Download Reports' }).click();
  await page.getByRole('combobox', { name: 'Report Type Select Report Type' }).click();
  await page.getByText('Returns Report').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'Collection Automation' }).click();
});