import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://cdms-staging.ripplr.in/login');
  await page.getByRole('textbox', { name: 'User ID User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID User ID' }).fill('admin@ripplr.in');
  await page.getByRole('textbox', { name: 'Password Password' }).click();
  await page.getByRole('textbox', { name: 'Password Password' }).fill('M@ver!ck');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('li').filter({ hasText: 'Logistics Management' }).click();
  await page.getByRole('link', { name: 'Return To Fc' }).click();
//   await page.getByRole('row', { name: '19/07/2025 KA8JD9302 Nikesh A' }).getByRole('link').click();
  await page.locator('.sc-evZas').nth(8).click();
  await page.getByText('Vehicle Allocated').first().click();
  await page.getByTitle('Delivered').locator('div').click();
//   await page.getByText('Delivered', { exact: true }).nth(1).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'right Delivery Details' }).click();
  await page.getByRole('button', { name: 'right Delivery Details' }).click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('radio', { name: 'Invoice Returned' }).check();
  await page.getByRole('button', { name: 'right Collection Details:' }).click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByText('Vehicle Allocated').first().click();
  await page.getByText('Delivered', { exact: true }).nth(1).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'right Delivery Details' }).click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('radio', { name: 'Invoice Returned' }).check();
  await page.getByRole('button', { name: 'right Collection Details:' }).click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByText('Vehicle Allocated').click();
  await page.getByText('Delivered', { exact: true }).nth(2).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'right Delivery Details' }).click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('radio', { name: 'Invoice Returned' }).check();
  await page.getByRole('button', { name: 'right Collection Details:' }).click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('row', { name: 'Nagaraj Patil E250003967 10/' }).locator('circle').nth(1).click();
  await page.getByRole('row', { name: 'Nagaraj Patil E250003967 10/' }).locator('circle').nth(1).click();
  await page.getByRole('row', { name: 'Nagaraj Patil E250003967 10/' }).locator('circle').nth(1).click();
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'Upload', exact: true }).click();
  await page.getByRole('button', { name: 'Choose File', exact: true }).click();
  await page.getByRole('button', { name: 'Choose File', exact: true }).setInputFiles('Billing (1)-1-11 (1) 11 pdf files (1) (5).pdf');
  await page.getByRole('button', { name: 'Upload', exact: true }).click();
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'Upload', exact: true }).click();
  await page.getByRole('button', { name: 'Choose File', exact: true }).click();
  await page.getByRole('button', { name: 'Choose File', exact: true }).setInputFiles('Billing (1)-1-11 (1) 11 pdf files (1) (5) (1).pdf');
  await page.getByRole('button', { name: 'Upload', exact: true }).click();
  await page.getByRole('button', { name: 'Verify' }).click();
});