import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://cdms-staging.ripplr.in/login');
  await page.getByRole('textbox', { name: 'User ID User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID User ID' }).fill('admin@ripplr.in');
  await page.getByRole('textbox', { name: 'Password Password' }).click();
  await page.getByRole('textbox', { name: 'Password Password' }).fill('M@ver!ck');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('Logistics Management').click();
  await page.getByRole('link', { name: 'Delivery Allocation' }).click();
  await page.getByRole('button', { name: 'Create Delivery Allocation' }).click();
  await page.getByRole('combobox', { name: 'FC(s) Select FC(s)' }).click();
  await page.getByRole('combobox', { name: 'FC(s) Select FC(s)' }).fill('btml');
  await page.getByText('BTML: BTM').click();
  await page.locator('label').filter({ hasText: 'Brands Select Brand(s)' }).locator('div').nth(2).click();
  await page.getByRole('combobox', { name: 'Brands Select Brand(s)' }).fill('bri');
  await page.getByText('BRIT: Britania').click();
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('listitem', { name: '2' }).locator('a').click();
  await page.locator('.ant-checkbox').nth(8).click();
  await page.locator('.ant-checkbox').nth(9).click();
  await page.locator('.ant-checkbox').nth(10).click();
  await page.getByRole('button', { name: 'Allocate Vehicle' }).click();
  await page.locator('.ant-form-item-control-input-content').first().click();
  await page.getByTitle('Both').locator('div').click();
  await page.locator('.ant-form-item-control-input-content').nth(1).click();
  await page.getByTitle('Regular').locator('div').click();
  await page.locator('.ant-form-item-control-input-content').nth(2).click();
  await page.getByText('Regular').nth(4).click();
  await page.getByRole('textbox', { name: '*Vehicle No' }).click();
  await page.getByRole('textbox', { name: '*Vehicle No' }).fill('KA8JD9302');
  await page.getByRole('textbox', { name: '*Driver', exact: true }).click();
  await page.getByRole('textbox', { name: '*Driver', exact: true }).fill('Nikesh A');
  await page.getByRole('textbox', { name: '*Vendor' }).click();
  await page.getByRole('textbox', { name: '*Vendor' }).fill('dfs');
  await page.locator('div').filter({ hasText: /^\*Driver Mobile Number$/ }).nth(2).click();
  await page.getByRole('textbox', { name: '*Driver Mobile Number' }).click();
  await page.getByRole('textbox', { name: '*Driver Mobile Number' }).fill('8840576893');
  await page.locator('.ant-form-item-control-input-content').last().click();
  await page.locator('.ant-form-item-control-input-content input').last().fill('del');
  await page.getByTitle('Delivery Boy').locator('div').click(); 
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.waitForTimeout(3000);
});